name: Update README with Repository Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub jinja2
          
      - name: Update README with repository data
        run: python .github/scripts/update_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "readme-bot@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest repository data"
          git push
